#!/usr/bin/env node


var fs = require('fs'),
	os = require('os');
exec = require('child_process').exec,
	path = "",
	home = process.env.HOME;


path = path.split('\n')[0];

var text = 'export PATH=$PATH:' + process.cwd() + '\n';

var bash_r;


//For mac-osx => ./bash_profile and linux => ./bash_rc
if (os.platform() == 'linux') {
	bash_r = '/.bashrc';
}
else {
	bash_r = '/.bash_profile';
}


var bashrcLocation = home + bash_r;

fs.appendFileSync(bashrcLocation, text);

exec("source " + bashrcLocation, null);

console.log('Done');
