#!/usr/bin/env node


var fs = require('fs'),
	exec = require('child_process').exec,
	path = "",
	home = process.env.HOME;


path = path.split('\n')[0];

var text = 'export PATH=$PATH:' + process.cwd() + '\n';

var bashrcLocation = home + '/.bashrc';

fs.appendFileSync(bashrcLocation, text);

exec("source " + bashrcLocation, null);

console.log('Done');
